### PR TITLE
GeoGebra calculator

### PR DESCRIPTION
**Pull request by davidfarmer**
Small adjustments to the calculator setup.

Added a button (next to "Index") to show/hide the calculator.
(Did not test on document lacking an index.)

See elsewhere for CSS and Javascript to make things work.
Note that Javascript version changed to 0.11.

Compile with
    --stringparam html.calculator geogebra-classic

Feel free to just copy my changes, or smash into one commit.

### CODE REVIEW

**Comment by davidfarmer** [comment]
Hiding the ToC when the calculator is open is not trivial.  Or maybe it is.
Either way, I'll look into that later.

**Comment by Alex-Jordan** [comment]
Looks good. I can take this and make a clean PR out of it.
I will probably change the button template to be inline, 
without the `<xsl:attribute>` elements.

We will need aria attributes on the button.
Including I think in the add-on javascript for changing the label
when the button is toggled. I'll let you know with specifics.

Is it clear we want the button to be a `div` instead of a HTML `button`?

**Comment by davidfarmer** [comment]
> Is it clear we want the button to be a div instead of a HTML button?

The distinction I wanted to make is that it toggles a state,
instead of taking you to another page.

If accessibility is better as a button (people seeing it won't care)
then please make it a button.  The CSS probably is okay as-is,
but if not then I can easily adjust.

**Comment by Alex-Jordan** [comment]
@rbeezer Point of order about commits. 

Can I put this together for you as three commits? One by me, then one by David, then one by me? No good way to combine my pre- and post-David edits into one commit.

**Comment by rbeezer** [comment]
Yes, that'd be fine.  I try to keep things neat and tidy, but credit is even 
more important.  I know how to change the author on a commit, so if necessary, I 
can do that.

**Pull request closed without merging**
